name: Check
on:
  push:
  pull_request:
permissions:
  contents: read
jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      ELECTRON_SKIP_BINARY_DOWNLOAD: '1'
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
        with:
          node-version: '24'
          package-manager-cache: false
      - run: npm install --global corepack@0.34.5
      - run: corepack pnpm install --frozen-lockfile
      - run: corepack pnpm check
      - run: corepack pnpm test
      - run: corepack pnpm format:check
      - run: corepack pnpm build
